version: "3.8"
services:
    app:
        build: .
        image: node-first
        container_name: app
        ports:
            - "5000:5000"
        volumes:
            - ./:/app
        environment:
            - PORT=${PORT}
            - MONGO_URI=${MONGO_URI}
            - RABBITMQ_URl=${RABBITMQ_URl}
            - REDIS_URI=${REDIS_URI}
        depends_on:
            - mongodb

            - rabibitmq
        networks:
            - mynetwork
    mongodb:
        image: mongo:latest
        container_name: mongodb_node
        ports:
            - "27017:27017"
        networks:
            - mynetwork
    rabibitmq:
        image: rabbitmq
        container_name: rabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"
        networks:
            - mynetwork
    redis:
        image: redis
        container_name: redis
        ports:
            - "6379:6379"
        networks:
            - mynetwork
networks:
    mynetwork:
        driver: bridge
